Feature: Pairing
    Pairing is the process by which you share a pairing token, generated by the app, with the Bisq
    client. The pairing token contains the device identifier as well as a private key to encrypt
    the notification messages. It is also possible to erase the pairing remotely from the Bisq
    client.

    Scenario: Erase pairing while app is running in foreground
        Given the app has been paired
        And the app is running in the foreground
        When clicking the erase button in either the Bisq client or bisqremote tool
        Then the app will load the Welcome view
        And show a toast message indicating the app was unpaired remotely

    Scenario: Erase pairing while app is running in background or is closed
        Given the app has been paired
        And the app is running in the background or is closed
        When clicking the erase button in either the Bisq client or bisqremote tool
        Then a notification will be shown in the system notification area
        And upon clicking the notification it will load the Welcome view
        And show a toast message indicating the app was unpaired remotely

    Scenario: Erase pairing removes existing notifications
        Given the app has been paired
        And has existing notifications
        When clicking the erase button in either the Bisq client or bisqremote tool
        And following the process to pair the app again
        Then all previously received notifications will not exist

    Scenario: Pairing after the app has been put in the background then foreground
        Given the app is not paired
        And the pairing token has been scanned or transferred
        And the app is placed in the background
        And the app is placed in the foreground
        When the pairing process is performed
        Then the app is paired successfully
