name: 'Get AVD Info'
description: 'Get the Android Virtual Device (AVD) info based on its API level.'
inputs:
    api-level:
        description: The API level for which to retrieve AVD info
        required: true
outputs:
    target:
        description: Target of the system image
        value: ${{ steps.get-avd-target.outputs.target }}
    arch:
        description: CPU architecture of the system image
        value: ${{ steps.get-avd-arch.outputs.arch }}
runs:
    using: "composite"
    steps:
        # Prefer ATD system images available in API 30+ as they are optimized for headless automated tests
        # Otherwise use the google_apis system image since Google Play Services is required
        # API 27 does not provide a google_apis system image and API 34 does not yet provide a
        # google_atd system image
        -   id: get-avd-target
            run: echo "target=$(if [ ${{ inputs.api-level }} -eq 34 ]; then echo google_apis; elif [ ${{ inputs.api-level }} -eq 27 ]; then echo default; elif [ ${{ inputs.api-level }} -ge 30 ]; then echo google_atd; else echo google_apis; fi)" >> $GITHUB_OUTPUT
            shell: bash
        # Prefer x86_64 architecture
        -   id: get-avd-arch
            run: echo "arch=x86_64" >> $GITHUB_OUTPUT
            shell: bash
