name: 'Get AVD Info'
description: 'Get the Android Virtual Device (AVD) info based on its API level.'
inputs:
    api-level:
        description: The API level for which to retrieve AVD info
        required: true
outputs:
    target:
        description: Target of the system image
        value: ${{ steps.get-avd-target.outputs.target }}
    arch:
        description: CPU architecture of the system image
        value: ${{ steps.get-avd-arch.outputs.arch }}
runs:
    using: "composite"
    steps:
        # Prefer ATD system images available in API 30+ as they are optimized for headless tests.
        # Google Play services is required and is available in the google_atd and google_apis images.
        # Note:
        #  - API 27 does not provide a google_apis system image.
        #  - Newer API's may not yet provide an ATD system image.
        -   id: get-avd-target
            shell: bash
            run: |
                set -euo pipefail
                api="${{ inputs.api-level }}"
                target="google_apis"
                if [[ "$api" -eq 27 ]]; then
                    target="default"
                elif [[ "$api" -ge 30 ]] && sdkmanager --list | grep -q "system-images;android-$api;google_atd;"; then
                    target="google_atd"
                fi
                echo "target=$target" >> "$GITHUB_OUTPUT"
        # Prefer x86_64 architecture
        -   id: get-avd-arch
            shell: bash
            run: echo "arch=x86_64" >> $GITHUB_OUTPUT
